### PR TITLE
To provide compatibility with cmake >= 2.8

### LINKED ISSUE #1: Provide support for cmake 2.8
Some Linux distributions, especially server distributions, still has older cmake versions than 3.5 by default. Cent OS 7.4 is an example:
```
$ cmake --version
cmake version 2.8.12.2
```
Yocto is another example:
```
# cmake --version
cmake version 3.3.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
Please, provide compatibility with older versions of cmake starting from 2.8 to extend Linux distributions coverage. Mind that currently gmmlib does not actually has dependency from cmake 3.5 and can be built with cmake 2.8 just fine.

### PR DESCRIPTION
**Pull request by dvrogozh**
Fixes #1

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
LGTM

**Comment by uartie** [comment]
I get the following cmake error with this patch and cmake 2.8.12 on Ubuntu Trusty:

```-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
*BUILD_TYPE not defined, default to: release
platform: Linux
source_dir: /opt/media/build/gmmlib/Source/GmmLib
arch: 64
build type: Release
SourceConfiguration:
CommonDir: /opt/media/build/gmmlib/Source/Common
IncDir: /opt/media/build/gmmlib/Source/inc
CMake Error at Tools/bldsys/include/utils.cmake:282 (continue):
  Unknown CMake command "continue".
Call Stack (most recent call first):
  Source/GmmLib/CMakeLists.txt:438 (bs_set_extra_target_properties)


-- Configuring incomplete, errors occurred!
See also "/opt/media/build/gmmlib/build/CMakeFiles/CMakeOutput.log".
```

**Comment by dvrogozh** [comment]
I fixed that for media-driver, but managed to miss for gmmlib. @uartie: how you configure and build gmmlib separately from media-driver? can you write your steps, please?

**Comment by uartie** [comment]
I'm using the build instructions in README.rst without any cmake options (i.e. cmake ../GmmLib) and same for driver README.md

**Comment by dvrogozh** [comment]
Got it. Fixed. There are duplicated scripts between gmmlib and media-driver. If you build media-driver scripts from gmmlib are not actually used.

**Comment by uartie** [comment]
That's odd... for me, if I don't build gmmlib first (separately), then media-driver fails to compile.

**Comment by uartie** [comment]
Nonetheless, your updated patch works for me now.. Thanks.

LGTM

**Comment by dvrogozh** [comment]
I build media-driver as:
```
cmake ../media-driver \
  -DMEDIA_VERSION="2.0.0" \
  -DBUILD_ALONG_WITH_CMRTLIB=1 \
  -DBS_DIR_GMMLIB=`pwd`/../gmmlib/Source/GmmLib/ \
  -DBS_DIR_COMMON=`pwd`/../gmmlib/Source/Common/ \
  -DBS_DIR_INC=`pwd`/../gmmlib/Source/inc/ \
  -DBS_DIR_MEDIA=`pwd`/../media-driver \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
  -DINSTALL_DRIVER_SYSCONF=OFF \
  -DLIBVA_DRIVERS_PATH=/usr/lib64/dri
```
Do you have -DBS_DIR_GMMLIB in a configure line?

**Comment by uartie** [comment]
Hah yes, I guess I don't compile exactly like README :/...

My workspace layout is:
```
<workspace>/gmmlib
<workspace>/media-driver
```
...and compile:
```
mkdir <workspace>/gmmlib/build
cd <workspace>/gmmlib/build
cmake ../.
make -j8
```
then:
```
mkdir <workspace>/media-driver/build
cd <workspace>/media-driver/build
cmake -DMEDIA_VERSION="2.0.0" \
  -DBUILD_ALONG_WITH_CMRTLIB=1 \
  -DBS_DIR_GMMLIB=<workspace>/gmmlib/Source/GmmLib/ \
  -DBS_DIR_COMMON=<workspace>/gmmlib/Source/Common/ \
  -DBS_DIR_INC=<workspace>/gmmlib/Source/inc/ \
  -DBS_DIR_MEDIA=<workspace>/media-driver/ \
  -DINSTALL_DRIVER_SYSCONF=OFF \
  ../.
```

**Comment by uartie** [comment]
IMO, the build setup is quite unconventional.  Duplicate cmake scripts across projects are a bad idea (maintenance nightmare).  Seems git submodules would have been a better approach to avoid all this or make gmmlib installable so it can be detected through common configuration conventions.

But that is beyond the scope of this pull-request.  LGTM

**Comment by uartie** [comment]
My bad, it looks like aa11d6ada523b1188fa7bebd1014b16be998c1df is actually breaking my driver compilation.  I had cherry-picked your patches to master the first time I tried them.  The second time, I pulled your PR directly which doesn't have the breaking change on master.

**Comment by dvrogozh** [comment]
outdated + pushed incorrect update.

**Pull request closed without merging**
